_name_: wavenet
in_channels: 80
out_channels: 80
diffusion_step_embed_dim_in: 128
diffusion_step_embed_dim_mid: 512
diffusion_step_embed_dim_out: 512
res_channels: 512
skip_channels: 512
num_res_layers: 12
dilation_cycle: 1
